### ISSUE TITLE
Double entries on Items

### ISSUE THREAD

**Issue by white-haired-uncle** [matsjoyce/LotIWikiGen#15]
A lot of items are listed twice...

2.2 / 2.3
2.35/36
4.18/19
5.9/10
7.18/19
10.6/7
15.2/3
15.4/5
16.21/22
17.2/3
17.7/8
17.25/26
18.1/2
20.4/5
23.11/12
23.13/14
24.10/22
24.22/23
26.1/2

**Comment by matsjoyce** [comment]
The reason for the duplication is that those items are duplicated in LotI (for example https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/item_list.cfg#L2652 and https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/item_list.cfg#L10018 for the Ancient Armour of the Power of the Ancients). I'm not really sure why they are duplicated, it seems to have happened in https://github.com/Dugy/Legend_of_the_Invincibles/commit/32f2adffde02493f4185a289ca5e14b5ef4b50d2#diff-8b53214308376963a56f452e94cfe26e70cf0349e7ce49c50174dea2f1ceea81R9260-R9729 Might be worth raising with Dugy?

In the meantime, since they are technically different items, the script displays them separately. I could add a marker to the duplicates?

**Comment by white-haired-uncle** [comment]
I think it'd be worth pointing out.  I can see someone wanting to change something, but not realize it's defined in two places.

Just looks kind of weird.

**Comment by white-haired-uncle** [comment]
You know, the list of double items is remarkably close to the list of items in utils/item_list.cfg that have "rare_drop" associated with them.

**Comment by matsjoyce** [comment]
Yeah, that's true. Here's the list of rare items, and whether they are duplicated or not (followed by the value of the `rare_drop` attribute):
```
Ancient Armour of the Power of the Ancients True 1
Mystic Occult Armour of Carpathia True 1
Deathblade Inheritance False 1
Taxes True 1
Stormforce True 1
The Touch of God True 1
Exterminator's Dagger True 2
Black Pearl False 1
Sapphire False 1
Exterminator's Knives True 2
Glowing Flight True 1
Tome of Liches True 1
Despicable Heroism True 1
Godsmasher True 1
Lilith's Old Precious False 1
The Fighting Bull False 1
Wrath of the Pagan True 1
Exterminator's Scythe True 2
Exterminator's Ring True 2
Ring of Unearthly Existence True 1
Staff of Crelanu True 1
Doombringer True 1
The Decimator True 1
Ballista True 1
```

Duplicated does imply it's rare, but not the other way round.
